learning_logs/urls.py
from django.urls import path
from . import views

app_name='learning_logs'
urlpatterns=[
    path('',views.index,name='index'),
    path('topics',views.topics,name='topics'),
    path('topics/<int:topic_id>',views.topic,name='topic'),
    path('new_topic',views.new_topic,name='new_topic'),
    path('new_entry/<int:topic_id>',views.new_entry,name='new_entry'),
    path('edit_entry/<int:entry_id>',views.edit_entry,name='edit_entry'),
]

llog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls') ),
    path('users',include('users.urls') ),
]

users/urls.py
from django.urls import path , include
from . import views
app_name='users'


urlpatterns=[
    path('',include('django.contrib.auth.urls')),
    path('register',views.register,name= 'register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete = models.CASCADE)
    
    def __str__(self):
        return self.text 
        
class Entry(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    text=models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural='entries'
    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic , Entry

class TopicForm(forms.ModelForm):
    
    class Meta:
        
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        
class EntryForm(forms.ModelForm):
    
    class Meta:
        
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry'}
        widgets= {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render , redirect
from .models import Topic, Entry
from .forms import TopicForm , EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

def index(request):
    return render(request,'learning_logs/index.html')
    
@login_required
def topics(request):
    topics=Topic.objects.filter(owner=request.user).order_by('date_added')
    context={'topics': topics}
    return render(request,'learning_logs/topics.html',context)
    
@login_required      
def topic(request, topic_id):
    topic= Topic.objects.get(id=topic_id)
    if topic.owner !=request.user:
        raise Http404
        
    entries= topic.entry_set.order_by('-date_added')
    context={'topic': topic, 'entries':entries}
    return render(request,'learning_logs/topic.html',context)
    
@login_required      
def new_topic(request):

 
    if request.method != 'POST':
        
        form = TopicForm()
    else:
        form =TopicForm(data=request.POST)
        if form.is_valid():
            new_topic=form.save(commit=False)
            new_topic.owner=request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context={'form':form}
    return render(request,'learning_logs/new_topic.html',context)
    
            
@login_required      
def new_entry(request,topic_id):
    
    topic=Topic.objects.get(id=topic_id)

 
    if request.method != 'POST':
        
        form = EntryForm()
    else:
        form =EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context={'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)
    
@login_required    
def edit_entry(request,entry_id):
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    if topic.owner !=request.user:
        raise Http404
    if request.method != 'POST':
    
   
        form=EntryForm(instance=entry)
    else:
        form=EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context={'entry':entry , 'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import login

def register(request):
    if request.method!= 'POST':
        form= UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user= form.save()
            login(request,new_user)
            return redirect('learning_logs:index')

    context={'form':form}
    return render(request,'registration/register.html',context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
	<title> Learning log</title>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}

	<!-- <meta http-equiv="X-UA-Compatible" content="ie=edge"> -->
	<!-- <link rel="stylesheet" href= "{% static 'css/font-awesome.min.css' %}"> -->
	<!-- <link rel="stylesheet" href= "{% static 'css/bootstrap.css' %}"> -->
	<!-- <link rel="stylesheet" href= "{% static 'css/style.css' %}"> -->
		
</head>
	
<body>
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-2 border">
		<a class="navbar-brand" href="{%url 'learning_logs:index'%}"> Home </a>
		
		<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarCollapse" aria-controls="navbarCollapse"
			aria-expanded="false" aria-lable="Toggle navigation">
			<span class="navbar-toggler-icon">
			</span>
			
		</button>
		
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{%url 'learning_logs:topics'%}"> Topics </a>
				</li>
			</ul>
			<ul class="navbar-nav ml-auto">
				{%if user.is_authenticated%}
				<li class="nav-item">
					<span class="navbar-brand">Hello,{{user.username}}. </span>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{%url 'users:logout'%}"> Logout </a>
				</li>
		
				{%else%}
					
				<li class="nav-item">
				
					<a class="nav-link" href="{%url 'users:login'%}"> Login </a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{%url 'users:register'%}"> Register </a>
				</li>
				{%endif%}
				
				
			</ul>
		</div>
	</nav>
	<main role="main" class="container-fluid ">
		<div class="rounded mb-2  bg-dark text-light border-bottom">
		{% block page_header %}
        {% endblock page_header %}
		</div>
			
		<div>
			{% block content %}
			
			{% endblock content %}
		</div>
		
		
	</main>
		
  <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
  <!-- <script src="{% static 'js/tether.min.js' %}"></script> -->
  <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
  <!-- <script src="{% static 'https://cdn.ckeditor.com/4.7.1/standard/ckeditor.js' %}"></script> -->
  <!-- <script> -->
    <!-- CKEDITOR.replace('editor1'); -->
  <!-- </script>	 -->
</body>
	
	
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
<h2>  <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>  </h2>
<h4>  Edit Entry </h4>
{% endblock page_header %}

{% block content %}

 
 
 

 <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button class="btn btn-primary"  name="submit"> Save Changes </button>
	{% endbuttons %}
 </form>


{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
<!-- {% load bootstrap4 %} -->
<!-- {% load static %} -->
<!-- {% bootstrap_css %} -->
<!-- {% bootstrap_javascript jquery='full' %} -->
<!-- {% bootstrap_jquery %} -->
<!-- {% bootstrap_javascript %} -->



{% block page_header %}
<h1 class=" container-fluid text-center"> Learning log Site  </h1>
{% endblock page_header %}


{% block content %}

<div id="faradars" class=" container carousel slide" data-ride="carousel">
	<ul class="carousel-indicators">
		<li data-target="#faradars" data-slide-to="0" class="active"></li>
		<li data-target="#faradars" data-slide-to="1"></li>
		<li data-target="#faradars" data-slide-to="2"></li>
	</ul>
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img  src="{% static 'img/img1.jpg' %}" width="1100" height="500" >
			
			<div class="carousel-caption">
				<h3>Bootstrap 4</h3>
				<p>FaraDars Bootstrap 4 Video Tutorials</p>
				<a href="http://faradars.org" class="btn btn-danger">FaraDars.org</a>
			</div>
		</div>
		<div class="carousel-item">
			<img src="{% static 'img/img2.jpg' %}" width="1100" height="500" >
		</div>
		<div class="carousel-item">
			<img src="{% static "img/img3.jpg" %}" width="1100" height="500">
		</div>
	</div>
	<a class="carousel-control-prev" href="#faradars" data-slide="prev">
		<span class="carousel-control-prev-icon"></span>
	</a>
	<a class="carousel-control-next" href="#faradars" data-slide="next">
		<span class="carousel-control-next-icon"></span>
	</a>
</div>

<div>
<p> </p>
</div>
	
		
	<div class="jumbotron text-center">
		<h1>My First Bootstrap Page Degin By Mohammad Najafi</h1>
		<p class="lead">Resize this responsive page to see the effect!</p> 
	</div>
  
<div class=" mb-2 d-flex justify-content-around">
  
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'img/img1.jpg' %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'img/img2.jpg' %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{% static 'img/img3.jpg' %}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
  
</div>

<img class="rounded mx-auto d-block img-fluid" src="{% static 'img/img1.jpg' %}" alt="Responsive image">

<div class="container-fluid">



	<div class="card-body">
	  <div class="table-responsive">
		<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
		  <thead>
			<tr>
			  <th>Name</th>
			  <th>Position</th>
			  <th>Office</th>
			  <th>Age</th>
			  <th>Start date</th>
			  <th>Salary</th>
			</tr>
		  </thead>
		  <tfoot>
			<tr>
			  <th>Name</th>
			  <th>Position</th>
			  <th>Office</th>
			  <th>Age</th>
			  <th>Start date</th>
			  <th>Salary</th>
			</tr>
		  </tfoot>
		  <tbody>
			<tr>
			  <td>Tiger Nixon</td>
			  <td>System Architect</td>
			  <td>Edinburgh</td>
			  <td>61</td>
			  <td>2011/04/25</td>
			  <td>$320,800</td>
			</tr>
			<tr>
			  <td>Garrett Winters</td>
			  <td>Accountant</td>
			  <td>Tokyo</td>
			  <td>63</td>
			  <td>2011/07/25</td>
			  <td>$170,750</td>
			</tr>

		  </tbody>
		</table>
	  </div>
	</div>


 <!-- BUTTON WITH COLLAPSE -->
    <button class="btn btn-primary d-block mb-4" data-toggle="collapse" data-target="#collapse-btn-1">Read More</button>

    <div class="collapse" id="collapse-btn-1">
      <div class="card">
        <div class="card-block">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit eius libero quisquam nobis explicabo vel non necessitatibus ipsum doloribus cupiditate voluptate recusandae quo autem error debitis, sed, minima repellendus commodi.
        </div>
      </div>
    </div>

    <!-- ACCORDION -->
    <div id="accordion" role="tablist">
      <div class="card">
        <div class="card-header" role="tab" id="heading">
          <h5 class="mb-0"><a href="#collapse1" data-parent="#accordion" data-toggle="collapse">
            Collapse One
          </a></h5>
        </div>

        <div id="collapse1" class="collapse show">
          <div class="card-block">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis ea iste a doloremque, cumque, debitis eum vel ipsum architecto aut, recusandae totam ullam aperiam. Nesciunt expedita officiis animi quam corporis optio inventore facilis sint et nulla in, repellat debitis dolor at nisi quo, unde temporibus. Quos nisi nostrum officia, illo.
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-header" role="tab" id="heading">
          <h5 class="mb-0"><a href="#collapse2" data-parent="#accordion" data-toggle="collapse">
            Collapse Two
          </a></h5>
        </div>

        <div id="collapse2" class="collapse">
          <div class="card-block">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis ea iste a doloremque, cumque, debitis eum vel ipsum architecto aut, recusandae totam ullam aperiam. Nesciunt expedita officiis animi quam corporis optio inventore facilis sint et nulla in, repellat debitis dolor at nisi quo, unde temporibus. Quos nisi nostrum officia, illo.
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-header" role="tab" id="heading">
          <h5 class="mb-0"><a href="#collapse3" data-parent="#accordion" data-toggle="collapse">
            Collapse Three
          </a></h5>
        </div>

        <div id="collapse3" class="collapse">
          <div class="card-block">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis ea iste a doloremque, cumque, debitis eum vel ipsum architecto aut, recusandae totam ullam aperiam. Nesciunt expedita officiis animi quam corporis optio inventore facilis sint et nulla in, repellat debitis dolor at nisi quo, unde temporibus. Quos nisi nostrum officia, illo.
          </div>
        </div>
      </div>
    </div>
  </div>  
  

  <footer  class="bg-dark text-white mt-5 p-5">
    <div class="container">
      <div class="row">
        <div class="col">
          <p class="lead text-center">Copyright &copy; 2020 Blogen</p>
        </div>
      </div>
    </div>
  </footer>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
 <h3> Topic:  <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a> </h3>
 
  <h5> ADD A New Entry </h5>
{% endblock page_header %}

{% block content %}



 <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button class="btn btn-primary" name="submit"> Add Entry </button>
 </form>


{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
<h2>   ADD A New Topic </h2>

{% endblock page_header %}
{% block content %}



 <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	
	{% buttons %}
	<button class="btn btn-primary" name="submit"> Add topic </button>
	{% endbuttons %}
 </form>


{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h2> Topic : {{topic}}</h2>
{% endblock page_header %}

{% block content %}


<p>
 <a href="{% url 'learning_logs:new_entry' topic.id %}"> Add new Entry </a>
</p>

<h3> Entries: </h3>



<ul>
 {% for entry in entries %}
	<div class="card-mb-3">
		<h4 class="card-header">
			{{entry.date_added|date:'M d, Y H:i'}}
			<small>
				<a href="{% url 'learning_logs:edit_entry' entry.id %}"> Edit Entry </a>
			</small>
		</h4>
		<div class="card-body">
			{{entry.text|linebreaks}}
		</div>
	</div>


 {% empty %}
 <P> No Entry </P>
 {% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1> Topics</h1>
{% endblock page_header %}

{% block content %}




<ul>
 {% for topic in topics %}
	<li><h3>
	<a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
	</h3></li>
 {% empty %}
 <li><h3> No Topics </h3></li>
 {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic'%}"> Add a new topic
</a></h3>

{% endblock content %}